services:
  backend:
    build: ../backend
    container_name: infrastructure-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password

  minio:
    image: minio/minio
    container_name: infrastructure-minio
    ports:
      - "9000:9000"    # API (utilisé par boto3)
      - "9001:9001"    # Console web (navigateur)
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  redis:
    image: redis:alpine
    container_name: infrastructure-redis
  frontend:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ../frontend/public:/usr/share/nginx/html:ro

volumes:
  minio_data:
