version: '3.8'

services:
  backend:
    build: ../backend
    container_name: infrastructure-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - minio
    env_file:
      - .env

  minio:
    image: minio/minio
    container_name: infrastructure-minio
    ports:
      - "9000:9000"    # API (utilisé par boto3)
      - "9001:9001"    # Console web (navigateur)
    volumes:
      - minio_data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"  # 👈 obligatoire !

  redis:
    image: redis:alpine
    container_name: infrastructure-redis

  frontend:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ../frontend/public:/usr/share/nginx/html:ro

volumes:
  minio_data:
